# Generated by Django 4.2.5 on 2023-09-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
