# Generated by Django 4.2.5 on 2023-10-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_store', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
