# Generated by Django 4.2.5 on 2023-11-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='static/media/avatar'),
        ),
    ]
